CREATE TABLE Pessoa(
    USERNAME VARCHAR(255) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE U_Publico( USERNAME int primary key references Pessoa(USERNAME));

CREATE TABLE U_Admin( USERNAME int primary key references Pessoa(USERNAME),
NOME VARCHAR(255) NOT NULL,
CÓDIGO funcionário);


CREATE TABLE Filme (
    NOME VARCHAR(255) NOT NULL,
    ANO INT NOT NULL,
    ID_FILME INT PRIMARY KEY,
    DURAÇÃO INT NOT NULL,
    GÊNERO VARCHAR(255) NOT NULL,
    SINOPSE VARCHAR(255) NOT NULL,
    DIRETOR VARCHAR(255) NOT NULL,
    IDIOMA VARCHAR(255) NOT NULL,
    NOTA AGREGADA INT NOT NULL,
    //tags multivalorado
);

CREATE TABLE Tags (
    ID_FILME INT REFERENCES Filme(ID_FILME),
    TAG VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_FILME, TAG)
);

CREATE TABLE Avaliação(
    ID_FILME INT REFERENCES Filme(ID_FILME),
    USERNAME VARCHAR(255) REFERENCES Pessoa(USERNAME),
    NOTA INT NOT NULL,
    PRIMARY KEY(ID_FILME, USERNAME)
); //REVER

CREATE TABLE Membro (
    USERNAME VARCHAR(255) REFERENCES Pessoa(USERNAME),
    ID_FILME INT REFERENCES Filme(ID_FILME),
    PRIMARY KEY(USERNAME, ID_FILME)
); //REVER

